apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor-scanner-aqua.fullname" . }}
  labels:
{{ include "harbor-scanner-aqua.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "harbor-scanner-aqua.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "harbor-scanner-aqua.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: {{ template "harbor-scanner-aqua.imageRef" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          securityContext:
            privileged: false
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          env:
            - name: "SCANNER_LOG_LEVEL"
              value: {{ .Values.scanner.logLevel }}
            - name: "SCANNER_API_ADDR"
              value: ":{{ .Values.service.port }}"
            - name: "SCANNER_API_READ_TIMEOUT"
              value: {{ .Values.scanner.api.readTimeout }}
            - name: "SCANNER_API_WRITE_TIMEOUT"
              value: {{ .Values.scanner.api.writeTimeout }}
            - name: "SCANNER_API_IDLE_TIMEOUT"
              value: {{ .Values.scanner.api.idleTimeout }}
            - name: "SCANNER_AQUA_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "harbor-scanner-aqua.fullname" . }}
                  key: aqua_user
            - name: "SCANNER_AQUA_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "harbor-scanner-aqua.fullname" . }}
                  key: aqua_password
            - name: "SCANNER_AQUA_HOST"
              value: {{ .Values.scanner.aqua.host | quote }}
            - name: "SCANNER_AQUA_REGISTRY"
              value: {{ .Values.scanner.aqua.registry | quote }}
            - name: "SCANNER_AQUA_REPORTS_DIR"
              value: {{ .Values.scanner.aqua.reportsDir | quote }}
            {{- if .Values.scanner.api.tlsEnabled }}
            - name: "SCANNER_API_TLS_CERTIFICATE"
              value: "/certs/tls.crt"
            - name: "SCANNER_API_TLS_KEY"
              value: "/certs/tls.key"
            {{- end }}
          ports:
            - name: api-server
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/scanner/reports
              readOnly: false
            {{- if .Values.scanner.api.tlsEnabled }}
            - name: certs
              mountPath: /certs
              readOnly: true
            {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        {{- if .Values.scanner.api.tlsEnabled }}
        - name: certs
          secret:
            secretName: {{ include "harbor-scanner-aqua.fullname" . }}-tls
        {{- end }}
