apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor-scanner-aqua.fullname" . }}
  labels:
{{ include "harbor-scanner-aqua.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "harbor-scanner-aqua.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "harbor-scanner-aqua.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ include "harbor-scanner-aqua.fullname" . }}-registry
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      initContainers:
        - name: scannercli
          image: {{ template "harbor-scanner-aqua.scannerImageRef" . }}
          imagePullPolicy: {{ .Values.aqua.image.pullPolicy | quote }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - NET_RAW
          command:
            - cp
          args:
            - "/opt/aquasec/scannercli"
            - "/downloads/scannercli"
          {{- if .Values.initResources }}
          resources:
{{ toYaml .Values.initResources | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: scannercli
              mountPath: /downloads
      containers:
        - name: main
          image: {{ template "harbor-scanner-aqua.adapterImageRef" . }}
          imagePullPolicy: {{ .Values.scanner.image.pullPolicy | quote }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - NET_RAW
          env:
            - name: "SCANNER_LOG_LEVEL"
              value: {{ .Values.scanner.logLevel }}
            - name: "SCANNER_API_ADDR"
              value: ":{{ .Values.service.port }}"
            - name: "SCANNER_API_READ_TIMEOUT"
              value: {{ .Values.scanner.api.readTimeout }}
            - name: "SCANNER_API_WRITE_TIMEOUT"
              value: {{ .Values.scanner.api.writeTimeout }}
            - name: "SCANNER_API_IDLE_TIMEOUT"
              value: {{ .Values.scanner.api.idleTimeout }}
            - name: "SCANNER_AQUA_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: {{ include "harbor-scanner-aqua.fullname" . }}
                  key: aqua_username
            - name: "SCANNER_AQUA_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "harbor-scanner-aqua.fullname" . }}
                  key: aqua_password
            - name: "SCANNER_AQUA_HOST"
              value: {{ .Values.scanner.aqua.host | quote }}
            - name: "SCANNER_AQUA_REGISTRY"
              value: {{ .Values.scanner.aqua.registry | quote }}
            - name: "SCANNER_CLI_NO_VERIFY"
              value: {{ .Values.scanner.aqua.scannerCLINoVerify | default false | quote }}
            - name: "SCANNER_CLI_SHOW_NEGLIGIBLE"
              value: {{ .Values.scanner.aqua.scannerCLIShowNegligible | default true | quote }}
            - name: "SCANNER_CLI_SHOW_WILL_NOT_FIX"
              value: {{ .Values.scanner.aqua.scannerCLIShowWillNotFix | default true | quote }}
            - name: "SCANNER_AQUA_REPORTS_DIR"
              value: {{ .Values.scanner.aqua.reportsDir | quote }}
            - name: "SCANNER_CLI_HIDE_BASE"
              value: {{ .Values.scanner.aqua.scannerCLIHideBase | default true | quote }}
            - name: "SCANNER_AQUA_USE_IMAGE_TAG"
              value: {{ .Values.scanner.aqua.useImageTag | quote }}
            - name: "SCANNER_STORE_REDIS_URL"
              value: {{ .Values.scanner.store.redisURL | quote }}
            - name: "SCANNER_STORE_REDIS_NAMESPACE"
              value: {{ .Values.scanner.store.redisNamespace | quote }}
            - name: "SCANNER_STORE_REDIS_POOL_MAX_ACTIVE"
              value: {{ .Values.scanner.store.redisPoolMaxActive | quote }}
            - name: "SCANNER_STORE_REDIS_POOL_MAX_IDLE"
              value: {{ .Values.scanner.store.redisPoolMaxIdle | quote }}
            - name: "SCANNER_STORE_REDIS_SCAN_JOB_TTL"
              value: {{ .Values.scanner.store.redisScanJobTTL | quote }}
            {{- if .Values.scanner.api.tlsEnabled }}
            - name: "SCANNER_API_TLS_CERTIFICATE"
              value: "/certs/tls.crt"
            - name: "SCANNER_API_TLS_KEY"
              value: "/certs/tls.key"
            {{- end }}
          ports:
            - name: api-server
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              scheme: {{ include "probeScheme" . }}
              path: /probe/healthy
              port: api-server
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              scheme: {{ include "probeScheme" . }}
              path: /probe/ready
              port: api-server
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- if .Values.mainResources }}
          resources:
{{ toYaml .Values.mainResources | indent 12 }}
          {{- end}}
          volumeMounts:
            - name: scannercli
              mountPath: /usr/local/bin/scannercli
              subPath: scannercli
            - name: data
              mountPath: /var/lib/scanner/reports
              readOnly: false
            - name: aqua
              mountPath: /opt/aquascans
              readOnly: false
            {{- if .Values.scanner.api.tlsEnabled }}
            - name: certs
              mountPath: /certs
              readOnly: true
            {{- end }}
      volumes:
        - name: scannercli
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: aqua
          emptyDir: {}
        {{- if .Values.scanner.api.tlsEnabled }}
        - name: certs
          secret:
            secretName: {{ include "harbor-scanner-aqua.fullname" . }}-tls
        {{- end }}
