apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}
type: Opaque
data:
    aqua_user: {{ required "Aqua user required!" .Values.scanner.aqua.user | b64enc | quote }}
    aqua_password: {{ required "Aqua password required!" .Values.scanner.aqua.password | b64enc | quote }}
