apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-scanner-aqua.fullname" . }}
  labels:
{{ include "harbor-scanner-aqua.labels" . | indent 4 }}
type: Opaque
data:
  aqua_username: {{ .Values.scanner.aqua.username | b64enc | quote }}
  aqua_password: {{ .Values.scanner.aqua.password | b64enc | quote }}
  aqua_token: {{ .Values.scanner.aqua.token | b64enc | quote }}
