nameOverride: ""
fullnameOverride: ""

service:
  type: "LoadBalancer"
  port: 8080

replicaCount: 1

image:
  registry: "docker.io"
  repository: "aquasec/harbor-scanner-aqua"
  tag: "0.1.0"
  pullPolicy: "IfNotPresent"

scanner:
  logLevel: info
  api:
    tlsEnabled: false
    tlsCertificate: ""
    tlsKey: ""
    readTimeout: 15s
    writeTimeout: 15s
    idleTimeout: 60s
  aqua:
    user: ""
    password: ""
    host: "http://csp-console-svc.aqua:8080"
    registry: "Harbor"
    reportsDir: "/var/lib/scanner/reports"
    useImageTag: true
  store:
    redisURL: "redis://harbor-harbor-redis:6379"
    redisNamespace: "harbor.scanner.aqua:store"
    redisPoolMaxActive: 5
    redisPoolMaxIdle: 5
    redisScanJobTTL: "1h"
