nameOverride: ""
fullnameOverride: ""

service:
  type: "ClusterIP"
  port: 8080

replicaCount: 1

initResources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

mainResources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi

aqua:
  version: 4.6
  registry:
    server: "registry.aquasec.com"
    username: ""
    password: ""
  image:
    pullPolicy: "IfNotPresent"

scanner:
  image:
    registry: "docker.io"
    repository: "aquasec/harbor-scanner-aqua"
    tag: "0.5.1"
    pullPolicy: "IfNotPresent"
  logLevel: info
  api:
    tlsEnabled: false
    tlsCertificate: ""
    tlsKey: ""
    readTimeout: 15s
    writeTimeout: 15s
    idleTimeout: 60s
  aqua:
    ## username Aqua management console username
    username: ""
    ## password Aqua management console password
    password: ""
    ## host Aqua management console address
    host: "http://csp-console-svc.aqua:8080"
    ## registry the name of the Harbor registry configured in Aqua management console
    registry: "Harbor"
    ## reportsDir directory to save temporary scan reports
    reportsDir: "/var/lib/scanner/reports"
    ## useImageTag the flag to determine whether the image tag or digest is used in the image reference passed to `scannercli`
    useImageTag: true
    ## scannerCLINoVerify the flag passed to `scannercli` to skip verifying TLS certificates
    scannerCLINoVerify: false
    ## scannerCLIShowNegligible the flag passed to `scannercli` to show negligible/unknown severity vulnerabilities
    scannerCLIShowNegligible: true
    ## scannerCLIShowWillNotFix the flag passed to `scannercli` to show vulnerabilities that will not be fixed
    scannerCLIShowWillNotFix: false
    ## scannerCLIHideBase the flag passed to `scannercli` to hide vulnerabilities in the base image
    scannerCLIHideBase: true
    ## scannerCLIOverrideRegistryCredentials the flag to enable passing `--registry-username` and `--registry-password`
    ## flags to the `scannercli` executable binary
    scannerCLIOverrideRegistryCredentials: false
  store:
    redisURL: "redis://harbor-harbor-redis:6379"
    redisNamespace: "harbor.scanner.aqua:store"
    redisPoolMaxActive: 5
    redisPoolMaxIdle: 5
    redisScanJobTTL: "1h"
