nameOverride: ""
fullnameOverride: ""

service:
  ## type Kubernetes service type
  type: "ClusterIP"
  ## port Kubernetes service port
  port: 8080

## replicaCount the number of scanner adapter Pods to run
replicaCount: 1

initResources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

mainResources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi

aqua:
  ## version the version of Aqua CSP that the adapter operates against
  version: 4.6
  registry:
    ## server the Aqua Docker registry server
    server: "registry.aquasec.com"
    ## username the Aqua Docker registry username
    username: ""
    ## password the Aqua Docker registry password
    password: ""
  image:
    pullPolicy: "IfNotPresent"

scanner:
  image:
    registry: "docker.io"
    repository: "aquasec/harbor-scanner-aqua"
    tag: "0.8.0"
    pullPolicy: "IfNotPresent"
  logLevel: info
  api:
    tlsEnabled: false
    tlsCertificate: ""
    tlsKey: ""
    readTimeout: 15s
    writeTimeout: 15s
    idleTimeout: 60s
  aqua:
    ## username Aqua management console username
    username: ""
    ## password Aqua management console password
    password: ""
    ## host Aqua management console address
    host: "http://csp-console-svc.aqua:8080"
    ## registry the name of the Harbor registry configured in Aqua management console
    registry: "Harbor"
    ## reportsDir directory to save temporary scan reports
    reportsDir: "/var/lib/scanner/reports"
    ## useImageTag the flag to determine whether the image tag or digest is used in the image reference passed to `scannercli`
    useImageTag: true
    ## scannerCLINoVerify the flag passed to `scannercli` to skip verifying TLS certificates
    scannerCLINoVerify: false
    ## scannerCLIShowNegligible the flag passed to `scannercli` to show negligible/unknown severity vulnerabilities
    scannerCLIShowNegligible: true
    ## scannerCLIOverrideRegistryCredentials the flag to enable passing `--robot-username` and `--robot-password`
    ## flags to the `scannercli` executable binary
    scannerCLIOverrideRegistryCredentials: false
  store:
    redisURL: "redis://harbor-harbor-redis:6379"
    redisNamespace: "harbor.scanner.aqua:store"
    redisPoolMaxActive: 5
    redisPoolMaxIdle: 5
    redisScanJobTTL: "1h"
