nameOverride: ""
fullnameOverride: ""

service:
  type: "LoadBalancer"
  port: 8080

replicaCount: 1

aqua:
  version: 4.5
  registry:
    server: "registry.aquasec.com"
    username: ""
    password: ""
  image:
    pullPolicy: "IfNotPresent"

scanner:
  image:
    registry: "docker.io"
    repository: "aquasec/harbor-scanner-aqua"
    tag: "0.2.0"
    pullPolicy: "IfNotPresent"
  logLevel: info
  api:
    tlsEnabled: false
    tlsCertificate: ""
    tlsKey: ""
    readTimeout: 15s
    writeTimeout: 15s
    idleTimeout: 60s
  aqua:
    username: ""
    password: ""
    host: "http://csp-console-svc.aqua:8080"
    registry: "Harbor"
    reportsDir: "/var/lib/scanner/reports"
    useImageTag: true
  store:
    redisURL: "redis://harbor-harbor-redis:6379"
    redisNamespace: "harbor.scanner.aqua:store"
    redisPoolMaxActive: 5
    redisPoolMaxIdle: 5
    redisScanJobTTL: "1h"
