nameOverride: ""
fullnameOverride: ""

service:
  type: "LoadBalancer"
  port: 8080

replicaCount: 1

image:
  registry: "docker.io"
  repository: "aquasec/harbor-scanner-aqua"
  tag: "0.1.0-rc2"
  pullPolicy: "IfNotPresent"

scanner:
  logLevel: info
  api:
    tlsEnabled: false
    tlsCertificate: ""
    tlsKey: ""
    readTimeout: 15s
    writeTimeout: 15s
    idleTimeout: 60s
  aqua:
    user: ""
    password: ""
    host: "http://aqua-web.aqua-security:8080"
    registry: "Harbor"
