---
name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
      - name: Run unit tests
        run: make test
      - name: Run integration tests
        run: make test-integration
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
      - name: Release snapshot
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v1.1.0
          args: release --snapshot --skip-publish --rm-dist
      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/aquasec/harbor-scanner-aqua:${{ github.sha }}"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
